Repository StepUp2025/TasteBox-Backend, pull requests merged in 2025-07, with the labels that each got.

#38 Chore: 브랜치 네이밍 규칙 확장 및 배포 브랜치 전략 적용
  .husky/pre-push
Labels: enhancement

#33 Feat: 사용자 취향 설정 및 조회 API 구현
  src/common/dto/content-list-query-dto.ts
  src/common/dto/pagination-query.dto.ts
  src/common/utils/tmdb.utils.ts
  src/genre/dto/genre.dto.ts
  src/genre/genre.module.ts
  src/genre/genre.repository.ts
  src/genre/genre.service.ts
  src/movie/dto/find-movie-detail-response.dto.ts
  src/movie/dto/find-movie-list-response.dto.ts
  src/movie/movie.controller.ts
  src/movie/movie.service.ts
  src/preference/dto/request/genre-ids.dto.ts
  src/preference/dto/request/update-preference-request.dto.ts
  src/preference/dto/response/get-preferences-response.dto.ts
  src/preference/dto/response/preference-detail.dto.ts
  src/preference/exceptions/genre-not-found.exception.ts
  src/preference/preference.controller.ts
  src/preference/preference.module.ts
  src/preference/preference.service.ts
  src/tv/dto/find-tv-detail-response.dto.ts
  src/tv/dto/find-tv-list-response.dto.ts
  src/tv/tv.controller.ts
  src/tv/tv.service.ts
  src/user/user.service.ts
Labels: documentation, enhancement

#43 Feat: SSM 기반 EC2 배포 전환 및 워크플로우 개선
  .github/workflows/deploy.yml
  infra/ec2-user-data/init.sh
Labels: enhancement

#48 Feat: 도커 컴포즈 및 배포 자동화 설정 변경
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: enhancement

#51 Feat: 스케줄러 동기화 날짜 추적용 엔티티 추가
  src/content/entities/sync-status.entity.ts
Labels: enhancement

#53 Feat: SyncStatus 엔티티를 모듈에 등록
  .env.example
  src/common/database/database.module.ts
  src/content/content.module.ts
Labels: enhancement

#55 Refactor: Tv를 TvSeries로 변경
  src/common/enums/content-type.enum.ts
  src/common/enums/source-type.enum.ts
  src/common/types/content-type.enum.ts
  src/common/types/source-type.enum.ts
  src/content/content.module.ts
  src/content/entities/content.entity.ts
  src/content/movie/dto/movie-detail-response.dto.ts
  src/content/movie/dto/movie-list-response.dto.ts
  src/content/movie/movie.service.ts
  src/content/movie/repository/movie.repository.ts
  src/content/tv-series/dto/tv-season-response.dto.ts
  src/content/tv-series/dto/tv-series-detail-response.dto.ts
  src/content/tv-series/dto/tv-series-list-item.dto.ts
  src/content/tv-series/dto/tv-series-list-response.dto.ts
  src/content/tv-series/entities/tv-season.entity.ts
  src/content/tv-series/entities/tv-series.entity.ts
  src/content/tv-series/repository/tv-series.repository.ts
  src/content/tv-series/tv-series.controller.ts
  src/content/tv-series/tv-series.service.ts
Labels: refactor

#62 Feat: 컬렉션 API 및 S3 모듈 구현
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/collection-contents/collection-contents.entity.ts
  src/collection-contents/collection-contents.module.ts
  src/collection/collection.controller.ts
  src/collection/collection.entity.ts
  src/collection/collection.module.ts
  src/collection/collection.repository.ts
  src/collection/collection.service.ts
  src/collection/dto/request/add-contents-request.dto.ts
  src/collection/dto/request/content-item.dto.ts
  src/collection/dto/request/contents-query.dto.ts
  src/collection/dto/request/create-collection-request.dto.ts
  src/collection/dto/request/remove-contents-request.dto.ts
  src/collection/dto/request/update-collection-request.dto.ts
  src/collection/dto/response/collection-detail-response.dto.ts
  src/collection/dto/response/collection-list-response.dto.ts
  src/collection/dto/response/collection-summary.dto.ts
  src/collection/dto/response/content-summary.dto.ts
  src/collection/entities/collection-content.entity.ts
  src/collection/entities/collection.entity.ts
  src/collection/exception/collection-delete-fail.exception.ts
  src/collection/exception/collection-not-found.exception.ts
  src/common/aws/exceptions/s3-delete-fail.exception.ts
  src/common/aws/exceptions/s3-upload-fail.exception.ts
  src/common/aws/s3.module.ts
  src/common/aws/s3.service.ts
  src/common/enums/s3.enum.ts
  src/common/exceptions/forbidden.exception.ts
  src/content/entities/content.entity.ts
  src/content/movie/entities/movie.entity.ts
  src/content/tv-series/entities/tv-series.entity.ts
  src/user/exceptions/user-not-found.exception.ts
  src/user/user.entity.ts
Labels: documentation, enhancement

#64 Fix: 컬렉션 생성 및 업데이트시 썸네일 업로드 관련 버그 수정
  src/collection/collection.controller.ts
  src/collection/collection.service.ts
Labels: bug

#75 컨텐츠 장르 조회 엔드포인트 인증 제거 및 문서 최신화
  src/genre/genre.controller.ts
Labels: bug

#77 Feat: 최근에 추가된 컨텐츠 목록 조회 시 limit를 Query로 받도록 수정
  src/collection/collection-content.repository.ts
  src/content/content.controller.ts
  src/content/content.service.ts
Labels: enhancement

#78 Fix: 컨텐츠 엔드포인트 수정
  src/content/content.controller.ts
Labels: bug

#85 Refactor: 표시 필드를 'displayTitle'로 통일
  src/content/movie/entities/movie.entity.ts
  src/content/tv-series/dto/tv-series-detail-response.dto.ts
  src/content/tv-series/entities/tv-series.entity.ts
Labels: bug, refactor

#88 Feat: Prometheus 및 Grafana를 통한 모니터링과 배포 자동화 적용
  .github/workflows/deploy.yml
  docker-compose.yml
  infra/ec2-user-data/init.sh
  infra/ec2-user-data/ssl-setup.md
  package-lock.json
  package.json
  prometheus/prometheus.yml
  src/app.module.ts
  src/common/interceptors/logging.interceptor.ts
Labels: enhancement
