Repository StepUp2025/TasteBox-Backend, pull requests merged in 2025-06, with the labels that each got.

#17 Feat: Auth 및 User API에 커스텀 예외 적용
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/exceptions/already-registered-account.exception.ts
  src/auth/exceptions/google-email-not-found.exception.ts
  src/auth/exceptions/invalid-credentials.exception.ts
  src/auth/exceptions/invalid-current-password.exception.ts
  src/auth/exceptions/invalid-refresh-token.exception.ts
  src/auth/exceptions/kakao-email-not-found.exception.ts
  src/auth/exceptions/oauth-account-login.exception.ts
  src/auth/exceptions/oauth-account-password-change.exception.ts
  src/auth/exceptions/password-mismatch.exception.ts
  src/auth/exceptions/strategy-config.exception.ts
  src/auth/strategies/google.strategy.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/kakao.strategy.ts
  src/auth/strategies/refresh.strategy.ts
  src/common/decorators/custom-api-exception.decorator.ts
  src/common/exceptions/bad-request.exception.ts
  src/common/exceptions/base.exception.ts
  src/common/exceptions/conflict.exception.ts
  src/common/exceptions/internal-server-error.exception.ts
  src/common/exceptions/not-found.exception.ts
  src/common/exceptions/unauthorized.exception.ts
  src/common/filters/http-exception.filter.ts
  src/common/utils/cookie.util.ts
  src/common/utils/nickname.util.ts
  src/user/exceptions/duplicate-email.exception.ts
  src/user/exceptions/duplicate-nickname.exception.ts
  src/user/exceptions/unique-nickname-generation.exception.ts
  src/user/exceptions/user-not-found.exception.ts
  src/user/user.controller.ts
  src/user/user.entity.ts
  src/user/user.repository.ts
  src/user/user.service.ts
  src/user/user.validator.ts
Labels: bug, documentation, enhancement

#29 Refactor: 응답 객체 키 네이밍을 camelCase로 변경
  src/movie/dto/find-movie-detail-response.dto.ts
  src/movie/dto/find-movie-list-response.dto.ts
  src/movie/dto/movie-list-item.dto.ts
  src/tv/dto/find-tv-detail-response.dto.ts
  src/tv/dto/find-tv-list-response.dto.ts
  src/tv/dto/tv-list-item.dto.ts
Labels: refactor

#31 Fix: useImportType 규칙 해제
  biome.json
  src/app.controller.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/jwt-auth/jwt-auth.guard.ts
  src/auth/guards/local-auth/local-user-only.guard.ts
  src/auth/strategies/google.strategy.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/kakao.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/auth/strategies/refresh.strategy.ts
  src/auth/types/request-with-user.interface.ts
  src/genre/genre.controller.ts
  src/genre/genre.repository.ts
  src/genre/genre.service.ts
  src/movie/movie.controller.ts
  src/movie/movie.service.ts
  src/tv/tv.controller.ts
  src/tv/tv.service.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: bug
